POST http://localhost:8080/match-history HTTP/1.1
Content-Type: application/json

{
	"p1_id": "sayi2",
	"p2_id": "saayi2",
	"winner" : "sayi2"
}

# DELETE http://localhost:8080/match-history/clear HTTP/1.1

# GET http://localhost:8080/match-history HTTP/1.1

